# Generated by Django 3.0.5 on 2021-04-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audibook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('narrator', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('uploaded_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file_type', models.CharField(max_length=100)),
                ('podcast_name', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('uploaded_date', models.DateTimeField()),
                ('host', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file_type', models.CharField(max_length=100)),
                ('song_name', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('uploaded_date', models.DateTimeField()),
            ],
        ),
    ]
