# Generated by Django 3.0.5 on 2021-04-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filed', '0003_auto_20210411_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audibook',
            name='audio_file_type',
            field=models.CharField(default='Audibook', max_length=100),
        ),
        migrations.AlterField(
            model_name='audibook',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='audio_file_type',
            field=models.CharField(default='Podcast', max_length=100),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file_type',
            field=models.CharField(default='Song', max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
