# Generated by Django 3.0.5 on 2021-04-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filed', '0004_auto_20210411_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audibook',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
