# Generated by Django 3.0.5 on 2021-04-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filed', '0005_auto_20210411_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
