# Generated by Django 3.0.5 on 2021-04-11 15:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filed', '0008_auto_20210411_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='participants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), default=list, size=10),
        ),
    ]
