# Generated by Django 3.0.5 on 2021-04-11 17:31

from django.db import migrations, models
import filed.models


class Migration(migrations.Migration):

    dependencies = [
        ('filed', '0009_auto_20210411_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('audio_file_type', models.CharField(default='Audiobook', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('narrator', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('uploaded_date', models.DateTimeField(validators=[filed.models.cannot_be_outdated])),
            ],
        ),
        migrations.DeleteModel(
            name='Audibook',
        ),
    ]
