# Generated by Django 3.0.5 on 2021-04-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filed', '0014_auto_20210412_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiobook',
            old_name='file_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='file_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='file_id',
            new_name='id',
        ),
    ]
